#
# ~/.bash_profile
#

[[ -f ~/.bashrc ]] && . ~/.bashrc

export PATH=$PATH:$HOME/.bin
export EDITOR="vim"
export TERMINAL="st"
export BROWSER="firefox"

#cat /etc/makepkg.conf | egrep -i "^(CFLAGS|CXXFLAGS|CPPFLAGS|LDFLAGS|MAKEFLAGS|CARCH|CHOST)"
### Set GCC Flags
export CARCH="x86_64"
export CHOST="x86_64-pc-linux-gnu"
export CPPFLAGS="-D_FORTIFY_SOURCE=2"
export CFLAGS="-march=native -O2 -pipe -fstack-protector-strong -fno-plt"
export CXXFLAGS="-march=native -O2 -pipe -fstack-protector-strong -fno-plt"
export LDFLAGS="-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now"
export MAKEFLAGS="-j4"

### Make QT Applications look like the gtk2 theme
export QT_QPA_PLATFORMTHEME="gtk2"

### Set Java Options for Font Rendering
export _JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=on -Dswing.aatext=true -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel'

### Global RDP cmd
export CRDP='xfreerdp /bpp:32 /kbd:0x00000407 /sound:sys:pulse /smartcard +clipboard +home-drive -wallpaper -themes +fonts -aero -window-drag -menu-anims /sec:nla'

### silver surfer (ag) extension for fzf
export FZF_DEFAULT_COMMAND='ag -g "" --hidden --ignore .git'
export FZF_DEFAULT_OPTS='--border'


if [[ "$(tty)" = "/dev/tty1" ]]; then
	pgrep -x i3 || startx
fi
