#!/bin/bash

if 	[[ "${BLOCK_BUTTON}" -eq 1 ]]; then
		pactl set-sink-mute 0 false
elif 	[[ "${BLOCK_BUTTON}" -eq 2 ]]; then
		pavucontrol --tab 3
elif 	[[ "${BLOCK_BUTTON}" -eq 3 ]]; then
		pactl set-sink-mute 0 true
elif 	[[ "${BLOCK_BUTTON}" -eq 4 ]]; then
  		pactl set-sink-volume 0 +5%
elif 	[[ "${BLOCK_BUTTON}" -eq 5 ]]; then
		pactl set-sink-volume 0 -5%
fi

statusLine=$(amixer get Master | tail -n 1)
status=$(echo "${statusLine}" | grep -wo "on")
volume=$(echo "${statusLine}" | awk -F ' ' '{print $5}' | tr -d '[]%')

if [[ "${status}" == "on" ]]; then
  echo "<span color='#00FFFF'></span><span color='#dfe3ee'> ${volume}%</span>"
  echo "<span color='#00FFFF'></span><span color='#dfe3ee'> ${volume}%</span>"
  echo ""
else
  echo "<span color='#00FFFF'></span>"
  echo "<span color='#00FFFF'></span>"
  echo ""
fi
